// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineLibrary.Data;

#nullable disable

namespace OnlineLibrary.Data.Migrations
{
    [DbContext(typeof(OnlineLibraryDbContext))]
    partial class OnlineLibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6f5de2f-4be6-4f7a-a3b5-c7c0d72ac8f1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a242145-60f2-4e35-8e5b-693a7d7bb6f4",
                            Email = "admin@onlinelibrary.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ONLINELIBRARY.COM",
                            NormalizedUserName = "ADMIN@ONLINELIBRARY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHIaJlSfhU4K8tmJOH0vNC1Seaj11r0efwD90KrvKI+D5PDGPPUoibcXFsK6Gfh1Yg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f5e9b60-7f08-4a84-9a2c-ec9d32f1cc7b",
                            TwoFactorEnabled = false,
                            UserName = "admin@onlinelibrary.com"
                        });
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abebfdd2-7a9e-4aa7-84b8-454b6ac74f1d"),
                            FullName = "Jane Austen"
                        },
                        new
                        {
                            Id = new Guid("9a17ee9f-f2c6-44f4-9247-ec5fcbec4f92"),
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = new Guid("2c5f78aa-7fca-46f7-a112-4db9d4c0d093"),
                            FullName = "Isaac Asimov"
                        },
                        new
                        {
                            Id = new Guid("fb1ac6db-3c36-4f35-bdce-8dcd4a61156e"),
                            FullName = "R.R. Tolkien"
                        },
                        new
                        {
                            Id = new Guid("f625bc9b-1b34-44fd-b88b-cbec15d529c6"),
                            FullName = "Agatha Christie"
                        });
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6f42e6f-6c1b-4b8f-bb2f-e87eb4fd8ecf"),
                            AddedByUserId = new Guid("d6f5de2f-4be6-4f7a-a3b5-c7c0d72ac8f1"),
                            CoverUrl = "https://upload.wikimedia.org/wikipedia/en/0/03/Prideandprejudiceposter.jpg",
                            DateAdded = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic novel about love and society in early 19th-century England.",
                            Genre = 0,
                            IsDeleted = false,
                            IsRead = true,
                            PublisherId = new Guid("7b1cb8a1-cce4-4fe8-b258-a03e3468b761"),
                            Rating = 5,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("0eea95e2-33be-4bf1-a851-84a040d4432a"),
                            AddedByUserId = new Guid("d6f5de2f-4be6-4f7a-a3b5-c7c0d72ac8f1"),
                            CoverUrl = "https://m.media-amazon.com/images/I/612ADI+BVlL._AC_UF1000,1000_QL80_.jpg",
                            DateAdded = new DateTime(2019, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dystopian novel about surveillance and totalitarianism.",
                            Genre = 4,
                            IsDeleted = false,
                            IsRead = true,
                            PublisherId = new Guid("67ad1f17-8e47-47ce-be56-9d7bc2c09736"),
                            Rating = 5,
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("9f5ce95b-c0cd-4f1f-bff3-c3571d003319"),
                            AddedByUserId = new Guid("d6f5de2f-4be6-4f7a-a3b5-c7c0d72ac8f1"),
                            CoverUrl = "https://cdn.mos.cms.futurecdn.net/oFCCtndaa9gxNqmJDY6Rp8.jpg",
                            DateAdded = new DateTime(2021, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Epic science fiction series about the fall and rise of galactic empires.",
                            Genre = 4,
                            IsDeleted = false,
                            IsRead = false,
                            PublisherId = new Guid("2da9d7ca-8f3f-4f0f-ab28-e84fc351338e"),
                            Rating = 0,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = new Guid("6e916262-b412-4232-8e4d-5f822f9da185"),
                            AddedByUserId = new Guid("d6f5de2f-4be6-4f7a-a3b5-c7c0d72ac8f1"),
                            CoverUrl = "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9458059_p_v10_ac.jpg",
                            DateAdded = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fantasy adventure preceding the events of The Lord of the Rings.",
                            Genre = 3,
                            IsDeleted = false,
                            IsRead = true,
                            PublisherId = new Guid("f2f4bc8f-b080-4624-8ba5-f64f0d006778"),
                            Rating = 5,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("3a1508af-90c6-4eb0-bec6-f7b5ea096d2d"),
                            AddedByUserId = new Guid("d6f5de2f-4be6-4f7a-a3b5-c7c0d72ac8f1"),
                            CoverUrl = "https://www.blackcat-cideb.com/uploads/2020/02/COVER_Murder_on_the_orient_express_Agatha-Christie_f2a379ae1e65e577f341258edaba4148.jpg",
                            DateAdded = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic mystery featuring detective Hercule Poirot.",
                            Genre = 2,
                            IsDeleted = false,
                            IsRead = false,
                            PublisherId = new Guid("e66f13fa-3f9b-4304-a450-7d0b907f22ec"),
                            Rating = 0,
                            Title = "Murder on the Orient Express"
                        });
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BooksAuthors");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("e6f42e6f-6c1b-4b8f-bb2f-e87eb4fd8ecf"),
                            AuthorId = new Guid("abebfdd2-7a9e-4aa7-84b8-454b6ac74f1d")
                        },
                        new
                        {
                            BookId = new Guid("0eea95e2-33be-4bf1-a851-84a040d4432a"),
                            AuthorId = new Guid("9a17ee9f-f2c6-44f4-9247-ec5fcbec4f92")
                        },
                        new
                        {
                            BookId = new Guid("9f5ce95b-c0cd-4f1f-bff3-c3571d003319"),
                            AuthorId = new Guid("2c5f78aa-7fca-46f7-a112-4db9d4c0d093")
                        },
                        new
                        {
                            BookId = new Guid("6e916262-b412-4232-8e4d-5f822f9da185"),
                            AuthorId = new Guid("fb1ac6db-3c36-4f35-bdce-8dcd4a61156e")
                        },
                        new
                        {
                            BookId = new Guid("3a1508af-90c6-4eb0-bec6-f7b5ea096d2d"),
                            AuthorId = new Guid("f625bc9b-1b34-44fd-b88b-cbec15d529c6")
                        });
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b1cb8a1-cce4-4fe8-b258-a03e3468b761"),
                            Name = "Apress"
                        },
                        new
                        {
                            Id = new Guid("67ad1f17-8e47-47ce-be56-9d7bc2c09736"),
                            Name = "Manning Publications"
                        },
                        new
                        {
                            Id = new Guid("2da9d7ca-8f3f-4f0f-ab28-e84fc351338e"),
                            Name = "O'Reilly Media"
                        },
                        new
                        {
                            Id = new Guid("f2f4bc8f-b080-4624-8ba5-f64f0d006778"),
                            Name = "Packt Publishing"
                        },
                        new
                        {
                            Id = new Guid("e66f13fa-3f9b-4304-a450-7d0b907f22ec"),
                            Name = "Addison-Wesley"
                        });
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.UserBook", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UsersBooks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OnlineLibrary.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OnlineLibrary.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLibrary.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OnlineLibrary.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.Book", b =>
                {
                    b.HasOne("OnlineLibrary.Data.Models.ApplicationUser", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLibrary.Data.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.BookAuthor", b =>
                {
                    b.HasOne("OnlineLibrary.Data.Models.Author", "Author")
                        .WithMany("BooksAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLibrary.Data.Models.Book", "Book")
                        .WithMany("BooksAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.UserBook", b =>
                {
                    b.HasOne("OnlineLibrary.Data.Models.Book", "Book")
                        .WithMany("UsersBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLibrary.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.Author", b =>
                {
                    b.Navigation("BooksAuthors");
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.Book", b =>
                {
                    b.Navigation("BooksAuthors");

                    b.Navigation("UsersBooks");
                });

            modelBuilder.Entity("OnlineLibrary.Data.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
